[package]
name = "ps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", features = [
    "image",
    "debug",
    "tokio_old",
    "svg",
    "canvas",
] }
iced_native = { git = "https://github.com/iced-rs/iced" }

native-dialog = "0.6.2"
svg = "0.10.0"
chrono = "0.4.19"
